#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
# 

name: OpenWrt-CI

on:
  push:
    branches: 
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean

          # 利用挂载在 /mnt/ 的 14G 额外空间:
          # sudo mkdir -p -m 777 /mnt/openwrt/bin /mnt/openwrt/build_dir/host /mnt/openwrt/build_dir/hostpkg /mnt/openwrt/dl /mnt/openwrt/feeds /mnt/openwrt/staging_dir
          # ln -s /mnt/openwrt/bin ./bin
          # mkdir -p ./build_dir/host && ln -s /mnt/openwrt/build_dir/host ./build_dir/host
          # mkdir -p ./build_dir/host && ln -s /mnt/openwrt/build_dir/hostpkg ./build_dir/hostpkg
          # ln -s /mnt/openwrt/dl ./dl
          # ln -s /mnt/openwrt/feeds ./feeds
          # ln -s /mnt/openwrt/staging_dir ./staging_dir

          df -h

      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          
      - name: Costom configure file
        run: |
          rm -f ./.config*
          touch ./.config         
          
          # 编译x86固件:
          cat >> .config <<EOF
          CONFIG_TARGET_x86=y
          CONFIG_TARGET_x86_legacy=y
          CONFIG_TARGET_x86_legacy_Generic=y
          CONFIG_PACKAGE_curl=y
          CONFIG_PACKAGE_htop=y
          CONFIG_PACKAGE_nano=y
          CONFIG_PACKAGE_wget=y
          EOF
          
          cat >> .config <<EOF
          CONFIG_PACKAGE_kmod-pcmcia-core=y
          CONFIG_PACKAGE_kmod-pcmcia-rsrc=y
          CONFIG_PACKAGE_kmod-pcmcia-bcm63xx=y
          CONFIG_PACKAGE_kmod-pcmcia-yenta=y
          CONFIG_PACKAGE_kmod-pcmcia-nozomi=y
          CONFIG_PACKAGE_kmod-rsi91x=y
          CONFIG_PACKAGE_kmod-rsi91x-sdio=y
          CONFIG_PACKAGE_kmod-rsi91x-usb=y
          CONFIG_PACKAGE_kmod-rt2400-pci=y
          CONFIG_PACKAGE_kmod-rt2500-pci=y
          CONFIG_PACKAGE_kmod-rt2500-usb=y
          CONFIG_PACKAGE_kmod-rt2800-mmio=y
          CONFIG_PACKAGE_kmod-rt2800-pci=y
          CONFIG_PACKAGE_kmod-rt2x00-mmio=y
          CONFIG_PACKAGE_kmod-rt2x00-pci=y
          CONFIG_PACKAGE_kmod-rt61-pci=y
          CONFIG_PACKAGE_kmod-rt73-usb=y
          CONFIG_PACKAGE_kmod-rtl8180=y
          CONFIG_PACKAGE_kmod-rtl8187=y
          CONFIG_PACKAGE_kmod-rtl8192c-common=y
          CONFIG_PACKAGE_kmod-rtl8192ce=y
          CONFIG_PACKAGE_kmod-rtl8192cu=y
          CONFIG_PACKAGE_kmod-rtl8192de=y
          CONFIG_PACKAGE_kmod-rtl8192se=y
          CONFIG_PACKAGE_kmod-rtl8812au-ct=y
          CONFIG_PACKAGE_kmod-rtl8821ae=y
          CONFIG_PACKAGE_kmod-rtl8xxxu=y
          CONFIG_PACKAGE_kmod-rtlwifi=y
          CONFIG_PACKAGE_kmod-rtlwifi-btcoexist=y
          CONFIG_PACKAGE_kmod-rtlwifi-pci=y
          CONFIG_PACKAGE_kmod-rtlwifi-usb=y
          CONFIG_PACKAGE_kmod-adm8211=y
          CONFIG_PACKAGE_kmod-ath6kl=y
          CONFIG_PACKAGE_kmod-ath6kl-sdio=y
          CONFIG_PACKAGE_kmod-ath6kl-usb=y
          CONFIG_PACKAGE_kmod-b43=y
          CONFIG_PACKAGE_kmod-b43legacy=y
          CONFIG_PACKAGE_kmod-bcma=y
          CONFIG_PACKAGE_kmod-br-netfilter=y
          CONFIG_PACKAGE_kmod-brcmfmac=y
          CONFIG_PACKAGE_kmod-brcmutil=y
          CONFIG_PACKAGE_rs9113-firmware=y
          CONFIG_PACKAGE_rt2800-pci-firmware=y
          CONFIG_PACKAGE_rt61-pci-firmware=y
          CONFIG_PACKAGE_rt73-usb-firmware=y
          CONFIG_PACKAGE_rtl8192ce-firmware=y
          CONFIG_PACKAGE_rtl8192cu-firmware=y
          CONFIG_PACKAGE_rtl8192de-firmware=y
          CONFIG_PACKAGE_rtl8192se-firmware=y
          CONFIG_PACKAGE_rtl8192su-firmware=y
          CONFIG_PACKAGE_rtl8821ae-firmware=y 
          CONFIG_PACKAGE_nfs-kernel-server=y
          CONFIG_PACKAGE_nfs-kernel-server-utils=y
          CONFIG_PACKAGE_nfs-server=y     
          CONFIG_PACKAGE_unfs3=y
          CONFIG_TARGET_KERNEL_PARTSIZE=16
          CONFIG_TARGET_ROOTFS_PARTSIZE=256
          EOF
          
      - name: Generate configuration file
        run: make defconfig

      - name: Make download
        run: |
          make download -j8
          find dl -size -1024c -exec rm -f {} \;

      - name: Compile firmware
        run: |
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
          du -h --max-depth=1 ./build_dir
          du -h --max-depth=1 ./bin

      - name: Prepare artifact
        run: find ./bin/targets/ -type d -name "packages" | xargs rm -rf {}

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt firmware
          path: ./bin/targets/
