# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#
# Copyright (C) 2019 P3TERX
#
# Copyright (C) 2020 KFERMercer
#
name: OpenWrt-CI

on:
  push:
    branches: 
      - master
  release:
    types: [published]

jobs:

  build_openwrt:

    name: Build OpenWrt firmware

    runs-on: ubuntu-latest

    if: github.event.repository.owner.id == github.event.sender.id

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php* android*
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf swig
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean

          df -h

      - name: Update feeds
        run: |
          sed -i 's/#src-git helloworld/src-git helloworld/g' ./feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          
      - name: Costom configure file
        run: |
          rm -f ./.config*
          touch ./.config         
          
          # 编译x86固件:
          cat >> .config <<EOF
          CONFIG_TARGET_x86=y
          CONFIG_TARGET_x86_legacy=y
          CONFIG_TARGET_x86_legacy_Generic=y
          CONFIG_PACKAGE_curl=y
          CONFIG_PACKAGE_htop=y
          CONFIG_PACKAGE_nano=y
          CONFIG_PACKAGE_wget=y
          EOF
          
          cat >> .config <<EOF
          CONFIG_PACKAGE_kmod-pcmcia-core=y
          CONFIG_PACKAGE_kmod-pcmcia-rsrc=y
          CONFIG_PACKAGE_kmod-pcmcia-bcm63xx=y
          CONFIG_PACKAGE_kmod-pcmcia-yenta=y
          CONFIG_PACKAGE_kmod-pcmcia-nozomi=y
          CONFIG_PACKAGE_kmod-rsi91x=y
          CONFIG_PACKAGE_kmod-rsi91x-sdio=y
          CONFIG_PACKAGE_kmod-rsi91x-usb=y
          CONFIG_PACKAGE_kmod-rt2400-pci=y
          CONFIG_PACKAGE_kmod-rt2500-pci=y
          CONFIG_PACKAGE_kmod-rt2500-usb=y
          CONFIG_PACKAGE_kmod-rt2800-mmio=y
          CONFIG_PACKAGE_kmod-rt2800-pci=y
          CONFIG_PACKAGE_kmod-rt2x00-mmio=y
          CONFIG_PACKAGE_kmod-rt2x00-pci=y
          CONFIG_PACKAGE_kmod-rt61-pci=y
          CONFIG_PACKAGE_kmod-rt73-usb=y
          CONFIG_PACKAGE_kmod-rtl8180=y
          CONFIG_PACKAGE_kmod-rtl8187=y
          CONFIG_PACKAGE_kmod-rtl8192c-common=y
          CONFIG_PACKAGE_kmod-rtl8192ce=y
          CONFIG_PACKAGE_kmod-rtl8192cu=y
          CONFIG_PACKAGE_kmod-rtl8192de=y
          CONFIG_PACKAGE_kmod-rtl8192se=y
          CONFIG_PACKAGE_kmod-rtl8812au-ct=y
          CONFIG_PACKAGE_kmod-rtl8821ae=y
          CONFIG_PACKAGE_kmod-rtl8xxxu=y
          CONFIG_PACKAGE_kmod-rtlwifi=y
          CONFIG_PACKAGE_kmod-rtlwifi-btcoexist=y
          CONFIG_PACKAGE_kmod-rtlwifi-pci=y
          CONFIG_PACKAGE_kmod-rtlwifi-usb=y
          CONFIG_PACKAGE_kmod-adm8211=y
          CONFIG_PACKAGE_kmod-ath6kl=y
          CONFIG_PACKAGE_kmod-ath6kl-sdio=y
          CONFIG_PACKAGE_kmod-ath6kl-usb=y
          CONFIG_PACKAGE_kmod-b43=y
          CONFIG_PACKAGE_kmod-b43legacy=y
          CONFIG_PACKAGE_kmod-bcma=y
          CONFIG_PACKAGE_kmod-br-netfilter=y
          CONFIG_PACKAGE_kmod-brcmfmac=y
          CONFIG_PACKAGE_kmod-brcmutil=y
          CONFIG_PACKAGE_rs9113-firmware=y
          CONFIG_PACKAGE_rt2800-pci-firmware=y
          CONFIG_PACKAGE_rt61-pci-firmware=y
          CONFIG_PACKAGE_rt73-usb-firmware=y
          CONFIG_PACKAGE_rtl8192ce-firmware=y
          CONFIG_PACKAGE_rtl8192cu-firmware=y
          CONFIG_PACKAGE_rtl8192de-firmware=y
          CONFIG_PACKAGE_rtl8192se-firmware=y
          CONFIG_PACKAGE_rtl8192su-firmware=y
          CONFIG_PACKAGE_rtl8821ae-firmware=y 
          CONFIG_PACKAGE_nfs-kernel-server=y
          CONFIG_PACKAGE_nfs-kernel-server-utils=y
          CONFIG_PACKAGE_nfs-server=y     
          CONFIG_PACKAGE_unfs3=y
          CONFIG_TARGET_KERNEL_PARTSIZE=16
          CONFIG_TARGET_ROOTFS_PARTSIZE=256
          EOF
          
      - name: Generate configuration file
        run: make defconfig

      - name: Make download
        run: |
          make download -j8
          find dl -size -1024c -exec rm -f {} \;

      - name: Compile firmware
        run: |
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
          du -h --max-depth=1 ./build_dir
          du -h --max-depth=1 ./bin

      - name: Prepare artifact
        run: |
          mkdir -p ./artifact/firmware
          mkdir -p ./artifact/package
          mkdir -p ./artifact/buildinfo
          rm -rf $(find ./bin/targets/ -type d -name "packages")
          cp -rf $(find ./bin/targets/ -type f) ./artifact/firmware/
          cp -rf $(find ./bin/packages/ -type f -name "*.ipk") ./artifact/package/
          cp -rf $(find ./bin/targets/ -type f -name "*.buildinfo" -o -name "*.manifest") ./artifact/buildinfo/

      - name: Deliver buildinfo
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_buildinfo
          path: ./artifact/buildinfo/

      - name: Deliver package
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_package
          path: ./artifact/package/

      - name: Deliver firmware
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_firmware
          path: ./bin/targets/
  

      - name: Upload release asset
        if: github.event == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.YOURTOKEN }}
          file: ./artifact/firmware/*
          tag: ${{ github.ref }}
          file_glob: true
